export const LOAD_QUESTIONS_SUCCESS = 'LOAD_QUESTIONS_SUCCESS';
export const LOAD_QUESTION_SUCCESS = 'LOAD_QUESTION_SUCCESS';
export const UPDATE_QUESTION_SUCCESS = 'UPDATE_QUESTION_SUCCESS';
export const LOAD_CURRENT_QUESTION_SUCCESS = 'LOAD_CURRENT_QUESTION_SUCCESS';
export const LOAD_PREVIOUS_QUESTION_SUCCESS = 'LOAD_PREVIOUS_QUESTION_SUCCESS';
export const LOAD_NEXT_QUESTION_SUCCESS = 'LOAD_NEXT_QUESTION_SUCCESS';